### ISSUE TITLE
Invalid syntax in wrapper.py on google cloud AI notebook

### ISSUE THREAD

**Issue by petrovichp** [bukosabino/ta#123]
When when I import the library to Google cloud Notebook runtime I get the following error, while there are no problems in other runtimes

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-7-eb5af8038f6c>", line 1, in <module>
    import ta

  File "/home/jupyter/ta/ta/__init__.py", line 8, in <module>
    from ta.wrapper import (add_all_ta_features, add_momentum_ta, add_others_ta,

  File "/home/jupyter/ta/ta/wrapper.py", line 46
    df[f'{colprefix}volume_adi'] = AccDistIndexIndicator(
                              ^
SyntaxError: invalid syntax

**Comment by bukosabino** [comment]
Hi @petrovichp ,

You should upgrade your Python version to 3.6 or greater.

Best,
Dario

**Comment by petrovichp** [comment]
Thank you very much!

пн, 24 февр. 2020 г., 16:51 Darío López Padial <notifications@github.com>:
