### ISSUE TITLE
FX historical data analysis

### ISSUE THREAD

**Issue by omidrshi** [bukosabino/ta#125]
Hi,
This is my forex historical data :

row|Timestamp|Open|High|Low|Close|Volume
------------ | ------------|------------- | -------------|------------ | -------------|---
0|20000530 172700 | 0.9302 | 0.9302|  0.9302 | 0.9302  |     0
1|20000530 173500 | 0.9304 | 0.9305 | 0.9304 | 0.9305  |     0
2|20000530 173800 | 0.9304 | 0.9304 | 0.9303 | 0.9303  |     0
3|20000530 174300 | 0.9301 | 0.9301|  0.9300 | 0.9300  |     0
4|20000530 174400|  0.9298 | 0.9298 | 0.9297  |0.9297|       0

* All volumes are 0!
* It has about 6.5 million rows!

when I run  "adding all features", I 'm getting this error :

`
df = ta.utils.dropna(data_df)
`
`
df = ta.add_all_ta_features(
    df, open="Open", high="High", low="Low", close="Close", volume="Volume")
`

> Traceback (most recent call last):
  File "c:/Users/OMID/Desktop/forex/main.py", line 8, in <module>
    df = ta.add_all_ta_features(df, open="Open", high="High", low="Low", close="Close", volume="Volume" , fillna=True)
  File "C:\Users\OMID\Desktop\forex\venv\lib\site-packages\ta\wrapper.py", line 307, in add_all_ta_features
    df = add_volume_ta(df=df, high=high, low=low, close=close, volume=volume, fillna=fillna, colprefix=colprefix)
  File "C:\Users\OMID\Desktop\forex\venv\lib\site-packages\ta\wrapper.py", line 72, in add_volume_ta
    close=df[close], volume=df[volume], fillna=fillna).negative_volume_index()
    self._run()
  File "C:\Users\OMID\Desktop\forex\venv\lib\site-packages\ta\volume.py", line 274, in _run
    self._nvi.iloc[0] = 1000
  File "C:\Users\OMID\Desktop\forex\venv\lib\site-packages\pandas\core\indexing.py", line 669, in __setitem__
  File "C:\Users\OMID\Desktop\forex\venv\lib\site-packages\pandas\core\indexing.py", line 2154, in _convert_to_indexer
    self._validate_key(obj, axis)
  File "C:\Users\OMID\Desktop\forex\venv\lib\site-packages\pandas\core\indexing.py", line 1993, in _validate_key
  File "C:\Users\OMID\Desktop\forex\venv\lib\site-packages\pandas\core\indexing.py", line 2062, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

where is the problem ?!

**Comment by gustavo-dev** [comment]
So, apparently "df = ta.utils.dropna(data_df)" is clearing all data in the data file. I was having the same problem and realized that and simply removed this line of code and it turned out to work fine. Give it a try
