### ISSUE TITLE
valueerror

### ISSUE THREAD

**Issue by arunsoman** [bukosabino/ta#153]
Traceback (most recent call last):
  File "/home/arun/PycharmProjects/stock2/taUtils.py", line 90, in <module>
    df = addTA(df)
  File "/home/arun/PycharmProjects/stock2/taUtils.py", line 16, in addTA
    df, open="Open", high="High", low="Low", close="Close", volume="Volume_BTC")
  File "/home/arun/.conda/envs/stock2/lib/python3.7/site-packages/ta/wrapper.py", line 325, in add_all_ta_features
    df = add_volatility_ta(df=df, high=high, low=low, close=close, fillna=fillna, colprefix=colprefix)
  File "/home/arun/.conda/envs/stock2/lib/python3.7/site-packages/ta/wrapper.py", line 104, in add_volatility_ta
    close=df[close], high=df[high], low=df[low], n=10, fillna=fillna).average_true_range()
  File "/home/arun/.conda/envs/stock2/lib/python3.7/site-packages/ta/volatility.py", line 37, in __init__
    self._run()
  File "/home/arun/.conda/envs/stock2/lib/python3.7/site-packages/ta/volatility.py", line 41, in _run
    tr = self._high.combine(cs, max) - self._low.combine(cs, min)
  File "/home/arun/.conda/envs/stock2/lib/python3.7/site-packages/pandas/core/series.py", line 2704, in combine
    new_values.append(func(lv, rv))
  File "/home/arun/.conda/envs/stock2/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

from talib.abstract import *
from ta import add_all_ta_features
from ta.utils import dropna

def addTA(df, delNaN = True):
    df = dropna(df)

    # Add all ta features
    df = add_all_ta_features(
        df, open="Open", high="High", low="Low", close="Close", volume="Volume_BTC")
    return df

if __name__ == '__main__':
    # loc = '/home/arun/rr/gpu/dataset/NSE_ADANI ENTERPRISES LIMITED.csv'
    loc = '/home/arun/Downloads/datas.csv'
    df = u.getAllFileAsDF (loc, i ='Timestamp')[0]
    #print(df.dtypes)
    print("********************")
    print(df.head(4))
    print(df.shape)
    df = addTA(df)
    #df = pd.concat([df, out], axis=1)
    print(df.shape)

**Comment by bukosabino** [comment]
Hi @arunsoman ,

I have fixed the issue. You need to update the library, using the last version (0.5.23)

```
pip install -U ta
```

or 

```
pip install ta==0.5.23
```

Please, let me know if you get some other errors.

Best,
Dario
