### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by antani** [bukosabino/ta#2]
While installing I get following error -
I am on Python 2.7.10

`pip install ta
Collecting ta
  Using cached https://files.pythonhosted.org/packages/68/29/e2b9a4ad5f8710a0913d9fc1abb52c5b89ecf7ea036f8a8d8e4e73b08009/ta-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/53/3syytbw50fnc0stv_tz8s7qwmcg7vv/T/pip-build-ESKw_I/ta/setup.py", line 21, in <module>
        classifiers = [],
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 390, in parse_config_files
        parser.read(filename)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 305, in read
        self._read(fp, filename)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 546, in _read
        raise e
    ConfigParser.ParsingError: File contains parsing errors: setup.cfg
    	[line  2]: '    description-file = README.md\n'`

**Comment by bukosabino** [comment]
I developed the library for python 3.

Please, use a virtualenv for python3:

```sh
> virtualenv -p python3 virtualenvironment
> source virtualenvironment/bin/activate
> pip install ta
```

Kind regards,
