### ISSUE TITLE
make lint not working anymore

### ISSUE THREAD

**Issue by N720720** [bukosabino/ta#233]
make lint

$ make lint
isort --check-only --recursive ta test
prospector test/
Traceback (most recent call last):
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyflakes 2.2.0 (/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages), Requirement.parse('pyflakes<2.4.0,>=2.3.0'), {'flake8'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.pyenv/versions/3.6.13/bin/prospector", line 33, in <module>
    sys.exit(load_entry_point('prospector==1.3.1', 'console_scripts', 'prospector')())
  File "/home/.pyenv/versions/3.6.13/bin/prospector", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 100, in load
    module = import_module(match.group('module'))
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prospector/run.py", line 8, in <module>
    from prospector import blender, postfilter, tools
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/prospector/blender.py", line 10, in <module>
    import pkg_resources
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyflakes 2.2.0 (/home/.pyenv/versions/3.6.13/lib/python3.6/site-packages), Requirement.parse('pyflakes<2.4.0,>=2.3.0'), {'flake8'})
make: *** [Makefile:14: lint] Error 1

**Comment by N720720** [comment]
I run into this problem in PR #232 while fixing Issue #321
