### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loc'

### ISSUE THREAD

**Issue by benglesII** [bukosabino/ta#245]
2021-04-21 00:21:59,016 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 86, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 382, in start
    preprocessed[pair] = trim_dataframe(df, timerange)
  File "/freqtrade/freqtrade/data/converter.py", line 128, in trim_dataframe
    df = df.loc[df[df_date_col] >= start, :]
AttributeError: 'NoneType' object has no attribute 'loc'

**Comment by benglesII** [comment]
missing return dataframe
