### ISSUE TITLE
Pandas problem 

### ISSUE THREAD

**Issue by peter-zigo-nxp** [bukosabino/ta#28]
Hi I have problem to generate average_true_range.

It looks that there is problem in pandas. 

I using python 3.6, pandas 0.23.4

(ta_2) c:\repos\ta_test\ta-master\examples_to_use>python all_features_example.py
Index(['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume_BTC',
       'Volume_Currency', 'Weighted_Price'],
      dtype='object')
Traceback (most recent call last):
  File "all_features_example.py", line 17, in <module>
    fillna=True)
  File "C:\Users\nxa18933\AppData\Local\Continuum\anaconda3\envs\ta_2\lib\site-packages\ta\wrapper.py", line 190, in add_all_ta_features
    df = add_volatility_ta(df, high, low, close, fillna=fillna)
  File "C:\Users\nxa18933\AppData\Local\Continuum\anaconda3\envs\ta_2\lib\site-packages\ta\wrapper.py", line 54, in add_volatility_ta
    n=14, fillna=fillna)
  File "C:\Users\nxa18933\AppData\Local\Continuum\anaconda3\envs\ta_2\lib\site-packages\ta\volatility.py", line 44, in average_true_range
    atr[i] = (atr[i-1] * (n-1) + tr[i]) / n
  File "C:\Users\nxa18933\AppData\Local\Continuum\anaconda3\envs\ta_2\lib\site-packages\pandas\core\series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\nxa18933\AppData\Local\Continuum\anaconda3\envs\ta_2\lib\site-packages\pandas\core\indexes\base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\_libs\index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 958, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 964, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 3

**Comment by bukosabino** [comment]
It was a bug in this library! 

It is fixed in new version 0.3.5:

> pip install ta==0.3.5
