### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'str' or KeyError: "['3,161.25' '3,147.20' '2,975.20' ... '10,600.25' '10,616.45' '10,619.55'] not in index"

### ISSUE THREAD

**Issue by sanjaykumar-e** [bukosabino/ta#37]
df = pd.read_csv('D:/GLIM/Empirical/Data/NIFTY_ta.csv')

df.head()
Out[132]: 
        Date      Open      High       Low     Close        Volume
0  10-Nov-08  2,973.30  3,161.25  2,973.30  3,148.25  25,07,00,000
1  11-Nov-08  3,147.20  3,147.20  2,919.45  2,938.65  22,16,54,000
2  12-Nov-08  2,937.90  2,975.20  2,794.95  2,848.45  25,04,60,000
3  14-Nov-08  2,848.00  2,938.80  2,778.80  2,810.35  25,67,42,000
4  17-Nov-08  2,813.40  2,835.70  2,694.50  2,799.55  25,12,20,000

**Error 1**

df2 = add_all_ta_features(df2, "Open", "High", "Low", "Close", "Volume", fillna=True)
Traceback (most recent call last):

  File "<ipython-input-135-f263c7e6b991>", line 1, in <module>
    df2 = add_all_ta_features(df2, "Open", "High", "Low", "Close", "Volume", fillna=True)

  File "D:\Setup Files\Anaconda3\lib\site-packages\ta\wrapper.py", line 185, in add_all_ta_features
    df = add_volume_ta(df, high, low, close, volume, fillna=fillna)

  File "D:\Setup Files\Anaconda3\lib\site-packages\ta\wrapper.py", line 26, in add_volume_ta
    df[volume], fillna=fillna)

  File "D:\Setup Files\Anaconda3\lib\site-packages\ta\volume.py", line 31, in acc_dist_index
    clv = ((close - low) - (high - close)) / (high - low)

  File "D:\Setup Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1066, in wrapper
    result = safe_na_op(lvalues, rvalues)

  File "D:\Setup Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1034, in safe_na_op
    lambda x: op(x, rvalues))

  File "pandas\_libs\algos_common_helper.pxi", line 1212, in pandas._libs.algos.arrmap_object

  File "D:\Setup Files\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1034, in <lambda>
    lambda x: op(x, rvalues))

TypeError: unsupported operand type(s) for -: 'str' and 'str'

**Error 2**

df2 = add_all_ta_features(df2, df2['Open'], df2['High'], df2['Low'], df2['Close'], df2['Volume'], fillna=True)
Traceback (most recent call last):

  File "<ipython-input-137-f4fb54d97c34>", line 1, in <module>
    df2 = add_all_ta_features(df2, df2['Open'], df2['High'], df2['Low'], df2['Close'], df2['Volume'], fillna=True)

  File "D:\Setup Files\Anaconda3\lib\site-packages\ta\wrapper.py", line 185, in add_all_ta_features
    df = add_volume_ta(df, high, low, close, volume, fillna=fillna)

  File "D:\Setup Files\Anaconda3\lib\site-packages\ta\wrapper.py", line 25, in add_volume_ta
    df['volume_adi'] = acc_dist_index(df[high], df[low], df[close],

  File "D:\Setup Files\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2679, in __getitem__
    return self._getitem_array(key)

  File "D:\Setup Files\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2723, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)

  File "D:\Setup Files\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))

KeyError: "['3,161.25' '3,147.20' '2,975.20' ... '10,600.25' '10,616.45' '10,619.55'] not in index"

**Comment by bukosabino** [comment]
Hi @sanjaykumar-e ,

A lot of new features were included in the library. Can you reproduce this error again?

Thank you.

**Comment by emptyopen** [comment]
Hi I'm getting this error as well. 

`KeyError: "None of [Float64Index([76.36, 75.88, 76.25, 74.82, 75.51, 76.33, 75.89, 75.11, 75.97,\n              76.56, 76.68, 76.15, 76.12, 77.35, 77.85, 76.91, 75.94, 76.38,\n              76.65, 76.85, 77.55,  77.5, 77.45, 78.31,  78.5, 79.49],\n             dtype='float64')] are in the [columns]"`

In response to `ta.add_all_ta_features`.

**Comment by bukosabino** [comment]
Hi @emptyopen 

Can you share more information? The code and the dataset would be great.

Best,
Dario

**Comment by emptyopen** [comment]
Hi, here's the code:

```
cursor = self.db['A'].find().sort([('date', pymongo.ASCENDING)])
        df = pd.DataFrame(list(cursor))
        print(df[['date', 'close', 'open', 'high', 'low', 'volume']])
        ta.add_all_ta_features(df, close=df['close'], open=df['open'], high=df['high'], low=df['low'], volume=df['volume'], fillna=True)
        print(df)
```

results in:

```
Traceback (most recent call last):
  File "C:/Users/Takkeezi/PycharmProjects/capitVita/application.py", line 13, in <module>
    calculator.calculate_indicators()
  File "C:\Users\Takkeezi\PycharmProjects\capitVita\DataCalculator\DataCalculator.py", line 48, in calculate_indicators
    ta.add_all_ta_features(df, close=df['close'], open=df['open'], high=df['high'], low=df['low'], volume=df['volume'], fillna=True)
  File "C:\Users\Takkeezi\Anaconda3\lib\site-packages\ta\wrapper.py", line 290, in add_all_ta_features
    df = add_volume_ta(df=df, high=high, low=low, close=close, volume=volume, fillna=fillna, colprefix=colprefix)
  File "C:\Users\Takkeezi\Anaconda3\lib\site-packages\ta\wrapper.py", line 39, in add_volume_ta
    high=df[high], low=df[low], close=df[close], volume=df[volume], fillna=fillna).acc_dist_index()
  File "C:\Users\Takkeezi\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2986, in __getitem__
    indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
  File "C:\Users\Takkeezi\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1285, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "C:\Users\Takkeezi\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1092, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "C:\Users\Takkeezi\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1177, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)
KeyError: "None of [Float64Index([76.36, 75.88, 76.25, 74.82, 75.51, 76.33, 75.89, 75.11, 75.97,\n              76.56, 76.68, 76.15, 76.12, 77.35, 77.85, 76.91, 75.94, 76.38,\n              76.65, 76.85, 77.55,  77.5, 77.45, 78.31,  78.5, 79.49],\n             dtype='float64')] are in the [columns]"
```

**Comment by bukosabino** [comment]
Hi @emptyopen ,

The function `add_all_ta_features` waits for strings instead of pd.Series for OHLCV parameters. Please, try doing this:

```python
ta.add_all_ta_features(df, close='close', open='open', high='high', low='low', volume='volume', fillna=True)
```

I will add some documentation for these wrapper functions.

Best,
Dario
